"""platform games

Revision ID: 192c4e5299dd
Revises: 8f6e0758ed7e
Create Date: 2023-06-26 17:23:07.626736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192c4e5299dd'
down_revision = '8f6e0758ed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_platform_games_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_platform_games_platform_id_platforms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_games'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_games')
    # ### end Alembic commands ###
