"""updated game title unique rule

Revision ID: 56229294ce12
Revises: a947d016858b
Create Date: 2023-06-25 09:17:54.625659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56229294ce12'
down_revision = 'a947d016858b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('uq_games_title', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_games_title', ['title'])

    # ### end Alembic commands ###
