"""commented out tables

Revision ID: 60de847a54f5
Revises: 9fdf8e53ff26
Create Date: 2023-06-26 12:23:01.086549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60de847a54f5'
down_revision = '9fdf8e53ff26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threads')
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_followers_follower_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_followers_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_followers')
    )
    op.create_table('threads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_threads')
    )
    # ### end Alembic commands ###
