"""added platforms table

Revision ID: 70eef80f1309
Revises: a7a7979bc9be
Create Date: 2023-06-24 16:10:07.771065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70eef80f1309'
down_revision = 'a7a7979bc9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alternative_name', sa.String(), nullable=True),
    sa.Column('platform_logo', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('platform_family', sa.Integer(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform')),
    sa.UniqueConstraint('platform_id', name=op.f('uq_platform_platform_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform')
    # ### end Alembic commands ###
