"""updated community table

Revision ID: a76bd5d21189
Revises: 56229294ce12
Create Date: 2023-06-25 17:00:23.917988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76bd5d21189'
down_revision = '56229294ce12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
