"""updated relationship

Revision ID: a7a7979bc9be
Revises: d7900eeb6a65
Create Date: 2023-06-23 20:46:53.156137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a7979bc9be'
down_revision = 'd7900eeb6a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
