"""added platforms tables

Revision ID: a947d016858b
Revises: 70eef80f1309
Create Date: 2023-06-24 16:10:43.443932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a947d016858b'
down_revision = '70eef80f1309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alternative_name', sa.String(), nullable=True),
    sa.Column('platform_logo', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('platform_family', sa.Integer(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('platform_id', name=op.f('uq_platforms_platform_id'))
    )
    op.drop_table('platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('alternative_name', sa.VARCHAR(), nullable=True),
    sa.Column('platform_logo', sa.VARCHAR(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('generation', sa.INTEGER(), nullable=True),
    sa.Column('platform_family', sa.INTEGER(), nullable=True),
    sa.Column('abbreviation', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_platform'),
    sa.UniqueConstraint('platform_id', name='uq_platform_platform_id')
    )
    op.drop_table('platforms')
    # ### end Alembic commands ###
