"""updated tables

Revision ID: d1a31467ecd3
Revises: 192c4e5299dd
Create Date: 2023-06-27 11:32:14.211541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a31467ecd3'
down_revision = '192c4e5299dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_platform_communities_community_id_communities')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_platform_communities_platform_id_platforms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_communities'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('platform_communities')
    # ### end Alembic commands ###
