"""create tables

Revision ID: d7900eeb6a65
Revises: 64d7c9f14bb0
Create Date: 2023-06-23 18:37:07.805475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7900eeb6a65'
down_revision = '64d7c9f14bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_community_users_community_id_communities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_community_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_users'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_banner', sa.String(), nullable=True))
        batch_op.drop_column('page_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('page_banner')

    op.drop_table('community_users')
    # ### end Alembic commands ###
