"""added community game relationship

Revision ID: df950bb01fa3
Revises: d1a31467ecd3
Create Date: 2023-06-27 14:16:23.572832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df950bb01fa3'
down_revision = 'd1a31467ecd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_community_games_community_id_communities')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_community_games_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_games'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_games')
    # ### end Alembic commands ###
